Learned about getopts, basic outline of main function

diff --git a/sspush b/sspush
--- a/sspush
+++ b/sspush
@@ -3,7 +3,7 @@
 # sspush
 # Date: 5/9/2023
 #
-# A tool for macOS and Linux that pushes a screenshot/image 
+# A tool for macOS and Linux that pushes a screencapture/image/file 
 # to a remote web server of your choosing via scp.
 # 
 # by CtrlAltMech
@@ -12,6 +12,39 @@
 
 # Exit on error
 set -e
+
+# Main logic
+main () {
+    while getopts ':i:a:s:' OPTION; 
+    do
+        case "$OPTION" in
+            i)
+                arg="$OPTARG"
+                echo "Option a was chosen OPTARG = $OPTARG which is equal to arg = $arg"
+            ;;
+            
+            a)
+                arg="$OPTARG"
+                echo "Option b was chosen OPTARG = $OPTARG which is equal to arg = $arg"
+            ;;
+
+            s)
+                arg="$OPTARG"
+                echo "Option c was chosen OPTARG = $OPTARG which is equal to arg = $arg"
+            ;;
+            \?)
+                echo "Usage: $(basename $0) [-i] [-a] [-s] /optional/file/path/"
+                exit 1
+            ;;
+        esac
+    done
+
+    if [[ "$arg" == "" ]]; then
+        echo "No input file"
+    else
+        echo "Input is $arg"
+    fi
+}
 
 # Configuration path
 readonly CONFIG="$HOME/.sspushrc"
@@ -67,13 +100,40 @@ conf_make () {
     exit 0
 }
 
-# Initial check the config exists and all options set.
+# Checks info provided is correct and sets variables
 pre_check () {
+    # Mac options, will need to get appropriate options to suit both linux/mac
+    local option_pattern_full='^$|^-b$|^-C$|^-i$|^-m$|^-v[g]?$'
+    local image_pattern='^-b$|^-C$|^-i$|^-m$'
+    local vid_pattern='^-v[g]?$'
+    disp_server="$(display_serv_check)"
+    os="$(os_check)"
+    
+    if [[ "$disp_server" == "wayland" ]]; then
+        copy_tool="$(wl-copy)"
+    elif [[ "$disp_server" == "x11" ]]; then 
+        copy_tool="$(xclip)"
+    elif [[ "$os" == "Darwin" ]]; then
+        copy_tool="$(pbcopy)"
+    else
+        echo "Unable to determine OS. Exiting..."
+        exit 1
+    fi
+
+    
     if ! [[ -f $CONFIG ]]; then
         conf_prompt
     else
-        . "$CONFIG" # Source the configuration file
+        . "$CONFIG" 
         conf_var_check 
+    fi
+
+    if ! [[ "$1" =~ $option_pattern_full ]]; then
+        echo "Your option doesn't match"
+        exit 1
+    else
+        arg="$1"
+        echo "Your option does match" 
     fi
 }
 
@@ -83,6 +143,15 @@ os_check () {
         echo "Darwin"
     elif [[ "$(uname -s)" == "Linux" ]]; then
         echo "Linux"
+    fi
+}
+
+# Checks which display server is running
+display_serv_check () {
+    if [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
+        echo "wayland"
+    elif [[ "$XDG_SESSION_TYPE" == "x11" ]]; then
+        echo "x11"
     fi
 }
 
@@ -97,6 +166,7 @@ conf_var_check () {
     : "${SERVER:?$msg}" 
     : "${BASELINK:?$msg}" 
     : "${NOTIFICATIONS:?$msg}" 
+    : "${CLIPBOARD:?$msg}" 
 } 
 
 # Creates the new randomly generated filename for the remote destination
@@ -124,6 +194,11 @@ mac_screencapture () {
        exit 1
     fi
     screencapture "$1" "$file_name" 
+}
+
+# Linux screencapture handler
+linux_screencapture () {
+    :
 }
 
 # Finds the file to push to remote server
@@ -156,23 +231,23 @@ push_logic () {
 }
 
 # Start of logic
-pre_check
-
-if [[ -z "$1" ]]; then # no options specified finds the most recent file in your screenshot folder
-    find_file
-    echo "Your most recent file is...$orig_file"
-    push_logic
-elif [[ "$#" == "1" && -e "$1" ]]; then # No option, only file selected to push
-    find_file "$1"
-    echo "Your selected file is $orig_file"
-    push_logic
-elif [[ $(os_check) == "Darwin" ]]; then
-    mac_screencapture "$1" "$2"
-    find_file
-    echo "Your selected file is $orig_file" 
-    push_logic
-elif [[ $(os_check) == "Linux" ]]; then
-    : # This is just a placeholder for linux support
-else
-    echo "Not a valid option."
-fi
+# main "$1"
+main "$@"
+# pre_check "$1"
+# find_file
+# echo "Your most recent file is...$orig_file"
+#push_logic
+# elif [[ "$#" == "1" && -e "$1" ]]; then # No option, only file selected to push
+#     find_file "$1"
+#     echo "Your selected file is $orig_file"
+#     push_logic
+# elif [[ $(os_check) == "Darwin" ]]; then
+#     mac_screencapture "$1" "$2"
+#     find_file
+#     echo "Your selected file is $orig_file" 
+#     push_logic
+# elif [[ $(os_check) == "Linux" ]]; then
+#     : # This is just a placeholder for linux support
+# else
+#     echo "Not a valid option."
+# fi
